name: Debug after merged
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  context:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo tag
        if: ${{ github.event.pull_request.merged && startsWith(github.head_ref, 'release-') }}
        run: |
          set -x
          git fetch --tag
          LATEST_TAG=$(git tag --sort=-v:refname | head -1)
          echo "${LATEST_TAG}"
