name: Test JSON
on:
  push:
    branches:
      - test-github-actions
  pull_request:
    paths:
      - '**.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format by prettier
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install prettier
        run: sudo npm install -g prettier
      - name: Display prettier
        run: prettier --version
      - name: Run prettier
        run: prettier --check --parser=json '**/*.json'
