name: Test Shell
on:
  push:
    branches:
      - test-github-actions
  pull_request:
    paths:
      - '**.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint by shellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install shellcheck
        run: docker pull koalaman/shellcheck
      - name: Display shellcheck
        run: docker run --rm koalaman/shellcheck --version
      - name: Run shellcheck
        run: find . -name "*.sh" | xargs docker run --rm -v $(pwd):/mnt koalaman/shellcheck
