name: Test YAML
on:
  push:
    branches:
      - test-github-actions
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint by yamllint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install yamllint
        run: sudo apt-get install yamllint
      - name: Display yamllint
        run: yamllint --version
      - name: Run yamllint
        run: yamllint --strict .
