name: Test Secret
on:
  push:
    branches:
      - test-github-actions
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secretlint:
    name: Lint by secretlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install secretlint
        run: docker pull secretlint/secretlint
      - name: Display secretlint
        run: docker run --rm secretlint/secretlint secretlint --version
      - name: Run secretlint
        run: docker run --rm -v $(pwd):/work -w /work secretlint/secretlint secretlint '**/*'
